### ISSUE TITLE
libjevents compilation fails

### ISSUE THREAD

**Issue by vmytnykx** [andikleen/pmu-tools#83]
The libjevents library fails because of https://github.com/andikleen/pmu-tools/commit/b8d1cbbc3b40b5d646cdf2a1d02db239eaedb53b#diff-b5627cf3207cd37fed88b9a04d95abbb commit. 
=====================================================
cc -g -Wall -O2  -I .. -Wno-unused-result  -L ..  rtest3.c rtest2.o  -ljevents -o rtest3
rtest2.o: In function `main':
/work-dir/pmu-tools/jevents/examples/rtest2.c:22: multiple definition of `main'
/tmp/ccfN1qxs.o:/work-dir/pmu-tools/jevents/examples/rtest3.c:26: first defined here
rtest2.o: In function `main':
/work-dir/pmu-tools/jevents/examples/rtest2.c:37: undefined reference to `sin'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'rtest3' failed
make[1]: *** [rtest3] Error 1
make[1]: Leaving directory '/work-dir/pmu-tools/jevents/examples'
Makefile:17: recipe for target 'all-examples' failed
make: *** [all-examples] Error

**Comment by andikleen** [comment]
Thanks. Fixed.

**Comment by vmytnykx** [comment]
Thanks @andikleen!
